### PR TITLE
Customizable password hashing strategies

### PR DESCRIPTION
**Pull request by steveklebanoff**
Allows the configuration of custom modules to encrypt/decrypt passwords

See feature request https://github.com/trenpixster/addict/issues/93

### CODE REVIEW

**Comment by trenpixster** [comment]
Sorry for the lack of feedback, I'll look at this shortly :)

**Comment by steveklebanoff** [comment]
Anything I can do to help get this pushed through?

**Comment by trenpixster** [comment]
@steveklebanoff this LGTM, thanks for implementing! I was going to suggest adopting the same flow that exists for the other Configs, but let's leave that for a future effort 👍

**Comment by steveklebanoff** [comment]
Cool, thanks for merging!  It would be nice to keep all the configs set up the same way, but I wasn't sure how to nicely modify the other variables set in `configs.ex` to support default values

**Pull request merged**
