### PR TITLE
Removed username

### PR DESCRIPTION
**Pull request by zmoshansky**
Would you consider dropping the username requirement? It is a breaking change. 
##### Motivation

Username doesn't serve any vital role within the user management system and removing it simplifies core user management and helps enforce a separation of concerns (which IMHO is a great thing). 
<br/>
##### But wait, what if I love usernames?

Likewise, it's easy enough for users to create an associated profile or account table which contains information like username, first_name, last_name, etc. This is a little more work but it keeps the system very concise and also allows users to implement the controllers around the additional functionality however they want without worrying about having to hack into the core user management.

### CODE REVIEW

**Comment by jontonsoup** [comment]
+1

**Comment by trenpixster** [comment]
That's actually a good point @zmoshansky, thanks for bringing it up, along with code too. I'll think about it for a while a get back to you :smile:

**Comment by optikfluffel** [comment]
What's the status on this?

**Comment by JimPanic** [comment]
Yes please can has?

**Comment by bredikhin** [comment]
+1

**Comment by sotte** [comment]
+1

**Comment by krishandley** [comment]
+1

**Comment by sebastian** [comment]
+1

**Comment by hatt** [comment]
+1

**Comment by ilsonlasmar** [comment]
+1

**Comment by trenpixster** [comment]
Yup, this is the way to go everyone, I'm sorry for the delay. I'm re-architecturing the library and this will be part of it. I won't merge this nevertheless for now. Thanks @zmoshansky for the heads up for this and everyone for the feedback :+1:

**Comment by trenpixster** [comment]
Added on #68, closing

**Pull request closed without merging**
