### PR TITLE
Support both text and html mails

### PR DESCRIPTION
**Pull request by c-rack**

### CODE REVIEW

**Comment by jxs** [comment]
Hi @c-rack, what if the templates were .eex files that were then rendered  on `send_email_to_user`? 
then it wouldn't matter the format as long as the template name/type was defined in the config

**Comment by c-rack** [comment]
Good idea @jxs !
In my patch, I just tried to add the functionality that I needed with minimal code change.
For EEx templates, we should open an issue to discuss the details. Do you want to open it or shall I?

**Comment by jxs** [comment]
i had already talked about that with @trenpixster ehe, imho we should open an issue to discuss that yeah, can you open it then pls? :)

**Comment by c-rack** [comment]
Closed in favor of #18

**Pull request closed without merging**
