### PR TITLE
bump ecto dep requirement

### PR DESCRIPTION
**Pull request by montague**

### CODE REVIEW

**Comment by dukex** [comment]
+1 @trenpixster any thought about this?

**Comment by suranyami** [comment]
+1 for merging this PR. There are already 3 forks of this repo that do just this.

I'd simplify the dep, though, to this:

``` elixir
{:ecto, "~> 1.0"},
```

since we don't necessarily need to track minor versions.

**Comment by optikfluffel** [comment]
:+1:

**Comment by trenpixster** [comment]
Thanks @montague! Care to define the dep as @suranyami proposed?

**Comment by montague** [comment]
comin right up!

**Comment by trenpixster** [comment]
Thanks! :+1:

**Pull request merged**
