### PR TITLE
render to json on plug instead of each handler

### PR DESCRIPTION
**Pull request by jxs**

### CODE REVIEW

**Comment by jxs** [comment]
do not merge pls

**Comment by trestrantham** [comment]
I'm in favor of this approach. It will also fit well into the current approach on https://github.com/trenpixster/addict/pull/24. Personally, I think we should add a `render_html/2` plug option as well and default to that (since we're including the view/templates in #24) while also including `render_json/2` as an available option. `render_html/2` will need some logic to determine how to respond to the request on success (redirect?) and failure (re-render the forms). What are your thoughts @trenpixster?

**Comment by jxs** [comment]
@trestrantham phoenix aleady brings a render function that can be used as a plug, look [here](http://www.phoenixframework.org/v0.9.0/docs/controllers) :P

**Comment by trestrantham** [comment]
@jxs Right. We'll need to wrap `render` to accommodate success/failure for each of our actions. Something like if LoginInteractor.run is success then redirect to page X, else re-render the form.

**Comment by jxs** [comment]
yup agreed :)

**Comment by trenpixster** [comment]
Closing for now due to refactor on #68, thanks for all @jxs!

**Pull request closed without merging**
